# Generated by Django 4.1.4 on 2022-12-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adv",
            old_name="imag",
            new_name="image",
        ),
    ]
