# Generated by Django 4.1.4 on 2022-12-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0002_rename_imag_adv_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adv",
            name="image",
        ),
    ]
